name: Cocoapods release
on:
  workflow_dispatch:
    inputs:
      pod:
        description: 'Pod name'     
        required: true
    
jobs:
  build:  
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push ${{ github.event.inputs.pod }}.podspec
